### ISSUE TITLE
Stacking column headers don't stretch

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-home#14]
When the window is very narrow the Maps and Other Information headers don't stretch across the whole page.

![screen shot 2014-10-27 at 6 29 11 am](https://cloud.githubusercontent.com/assets/7338435/4789350/1d46247a-5dc4-11e4-8195-ea00a2df1592.png)

**Comment by mlofgren** [comment]
fixed

**Comment by srsjojo** [comment]
:+1:
