### ISSUE TITLE
Gagulic Feedback

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-home#18]
Some things to think about:
- [x] Large gap between header image and "About the Agency" - doesn't "draw him in". Should there be something there about the site? Explaining what is below?
- [x] "the Agency" - should we decide which to use? VTrans? Agency of Transportation? Vermont Agency of Transportation? AOT?
- [ ] ~~We mention "poor" and "very poor" condition in the text, should we explain what that means? (like our methodology discussion?)~~ wontfix
- [x] "data" link vague. Should it say "get data" or "download data"? 
- [ ] Have a FAQ page (part of the "About" page maybe?)
- [x] Footer image size - is it the same importance as the header? Do we want them to leave? Should the button styles be a little different?
- [ ] ~~`visited` css class - change clicked link color~~
- [x] Standardize section titles - choose a schema. `asset + data + " Data"` maybe?
- [ ] ~~"Maps" and "Other Information" look like buttons~~

**Comment by srsjojo** [comment]
Passing to @mlofgren

**Comment by srsjojo** [comment]
Re: header-content bridge, look how this theme does it: http://startbootstrap.com/templates/stylish-portfolio/

**Comment by mlofgren** [comment]
-shrunk footer image and buttons
-added hr tag under header image for some separation.
