### ISSUE TITLE
add font-awesome buttons to redesigned content areas

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-home#4]
Colors:
App: #F22
Map: #393
Data: #F90
Gallery: #12F
Report: #09F
Contact: #F09

https://color.adobe.com/vtransparency-color-theme-4646529/

**Comment by srsjojo** [comment]
Maybe buttons like this?
![image](https://cloud.githubusercontent.com/assets/7338435/4756199/9fd42ab4-5acb-11e4-91aa-aded63a67339.png)

https://creativemarket.com/premiumcoding/72001-100-Flat-Modern-Web-Buttons-Set/screenshots/#screenshot1

**Comment by mlofgren** [comment]
done
