### ISSUE TITLE
Who do I call contact labels

### ISSUE THREAD

**Issue by filkee** [VTrans/vtp3-home#43]
I noticed that when you click on a road segment the regional construction manager comes up first and is labeled something like "regional manager" and then the DM and the DTA are below. The problem with this is that the RCM and DM are separate worlds. You don't want the construction managers getting calls about potholes. Should probably add "construction" and "maintenance" respectively.

Oh, look. It's bedtime.

**Comment by srsjojo** [comment]
:clap: :clap: 

:sleeping: :sleepy: :zzz:

**Comment by rkiniry** [comment]
Assigned to Evan, if the text is fixed, close it.

**Comment by srsjojo** [comment]
All good :v:
