### ISSUE TITLE
Have intro header buttons merge into the header when they reach the top of the page

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-home#7]
What if when the top buttons (Pavement, Projects, etc) reached the top of the page they stuck there and stayed on top?

**Comment by srsjojo** [comment]
Watch what happens to the buttons on the UC page when you scroll

http://www.esri.com/events/user-conference

**Comment by mlofgren** [comment]
Not sure about it. It would take up a lot of real-estate for little gains - especially if we add more buttons. The header is already static across the top - maybe we could have a select box as another option to get to the sections.

**Comment by srsjojo** [comment]
:+1: :100:
